In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("C:\\Users\\tgandhi\\Desktop\\dataScience\\data\\sqrAnalysisData.csv")

In [5]:
data.head()

,Unnamed: 0,"Metric Value - 4-Year Graduation Rate - Self-Contained, Integrated Co-Teaching, or SETSS",Metric Value - 4-Year Graduation Rate - English Language Learners,Metric Value - 4-Year Graduation Rate - Lowest Third Citywide,School Name,Metric Rating - 4-Year Graduation Rate,Metric Value - College and Career Preparatory Course Index,School Name.1,School Type,Enrollment,...,Percent Self-Contained,Economic Need Index,Percent Overage/Undercredited,Percent in Temp Housing,Percent HRA Eligible,Percent Asian,Percent Black,Percent Hispanic,Percent White,School Year
0,0,0.385,0.500,0.348,Henry Street School for International Studies,0.545,0.091,Henry Street School for International Studies,High School,160,...,0.013,0.881,0.113,0.225,0.638,0.131,0.225,0.600,0.038,2015_2016
1,1,0.611,0.739,0.524,University Neighborhood High School,0.758,0.561,University Neighborhood High School,High School,343,...,0.009,0.771,0.111,0.198,0.548,0.280,0.274,0.414,0.029,2015_2016
2,2,0.696,0.833,0.833,East Side Community School,0.844,0.856,East Side Community School,High School,386,...,0.005,0.591,0.003,0.057,0.420,0.122,0.210,0.554,0.083,2015_2016
3,3,0.150,0.250,0.235,Marta Valle High School,0.587,0.320,Marta Valle High School,High School,272,...,0.063,0.794,0.114,0.154,0.643,0.033,0.423,0.522,0.018,2015_2016
4,4,1.000,NaN,NaN,"New Explorations into Science, Technology and ...",0.995,0.984,"New Explorations into Science, Technology and ...",High School,655,...,0.000,0.278,0.012,0.032,0.232,0.359,0.119,0.179,0.310,2015_2016